apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
  namespace: grupo5-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
        - name: queue-service
          image: martupiru/queue-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: USER_BD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: PASSWORD_BD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/tickets
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              value: my-valkey-cluster-0.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-1.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-2.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-3.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-4.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-5.my-valkey-cluster-headless.default.svc.cluster.local:6379
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: SPRING_DATA_REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: grupo5-tickets
spec:
  type: ClusterIP
  selector:
    app: queue-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compra-service
  namespace: grupo5-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compra-service
  template:
    metadata:
      labels:
        app: compra-service
    spec:
      containers:
        - name: compra-service
          image: martupiru/compra-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: USER_BD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: PASSWORD_BD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/tickets
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              value: my-valkey-cluster-0.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-1.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-2.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-3.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-4.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-5.my-valkey-cluster-headless.default.svc.cluster.local:6379
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: SPRING_DATA_REDIS_PASSWORD
            - name: QUEUE_SERVICE_URL
              value: http://queue-service:8081
            - name: BUYING_SNAPSHOT_INTERVAL_MS
              value: "30000"
---
apiVersion: v1
kind: Service
metadata:
  name: compra-service
  namespace: grupo5-tickets
spec:
  type: ClusterIP
  selector:
    app: compra-service
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
  namespace: grupo5-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service
  template:
    metadata:
      labels:
        app: scheduler-service
    spec:
      containers:
        - name: scheduler-service
          image: martupiru/scheduler-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              value: my-valkey-cluster-0.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-1.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-2.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-3.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-4.my-valkey-cluster-headless.default.svc.cluster.local:6379,my-valkey-cluster-5.my-valkey-cluster-headless.default.svc.cluster.local:6379
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-secret
                  key: SPRING_DATA_REDIS_PASSWORD
            - name: COMPRA_SERVICE_URL
              value: http://compra-service:8083
            - name: QUEUE_SERVICE_URL
              value: http://queue-service:8081
            - name: SCHEDULER_INTERVAL_MS
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: grupo5-tickets
spec:
  type: ClusterIP
  selector:
    app: scheduler-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: grupo5-tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: martupiru/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: QUEUE_SERVICE_URL
              value: http://queue-service:8081
            - name: PURCHASE_SERVICE_URL
              value: http://compra-service:8083
            - name: CORS_ALLOWED_ORIGINS
              value: "http://10.66.1.52"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: grupo5-tickets
spec:
  type: LoadBalancer
  loadBalancerIP: 10.66.1.51
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080