server.port=8083
spring.application.name=compra-service

spring.datasource.url=jdbc:postgresql://localhost:5432/tickets
spring.datasource.username=gorditos
spring.datasource.password=cocacola
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
