spring.application.name=api-gateway
server.port=8080
#EN DOCKER
#queue.service.url=http://queue-service:8081
#purchase.service.url=http://compra-service:8083

#EN LOCAL
queue.service.url=http://localhost:8081
purchase.service.url=http://localhost:8083

#por si implementamos react
cors.allowed-origins=http://localhost:5173,http://localhost:3000

#Usamos openfeign para conectar los microservicios
# Logs de Feign: NONE | BASIC | HEADERS | FULL
feign.client.config.default.logger-level=BASIC

# Timeouts (ms). para conocer si los servicios estan caidos
feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=10000

#Actuators para monitoreo por ahora health e info. Ver si agregamos metrics, mappings, etc
logging.level.com.tickets.api_gateway=DEBUG
logging.level.com.tickets.api_gateway.client=DEBUG
#logs
logging.level.com.cine.apigateway=DEBUG
logging.level.com.cine.apigateway.client=DEBUG