appendonly yes #no pierdo cola si redis se reinicia
appendfsync everysec #cada segundo se sincroniza el archivo de persistencia, es un buen equilibrio entre seguridad y rendimiento
maxmemory-policy noeviction #no elimininar datos si se alcanza el límite de memoria, en su lugar se devuelve un error
port 6379 #puerto por defecto
loglevel notice #logs utiles para saber lo que pasa sin ser demasiado verbosos
save 60 1 #snapshot cada 60 segundos si al menos 1 clave ha cambiado