spring.application.name=scheduler-service
server.port=8082
server.servlet.context-path=/api

spring.data.redis.host=localhost
spring.data.redis.port=6379

# URLs de los otros servicios
compra-service.url=http://localhost:8083
queue-service.url=http://localhost:8081

# Intervalo del scheduler en ms
scheduler.interval.ms=5000